default:
  server:
    name: rest-api
    port: 8008
  AWS:
    region: eu-west-1
    endpoint: dynamodb.eu-west-1.amazonaws.com
  authentication:
    web_client_secret: xxx
    rest_api_secret: xxx
    android_client_secret: xxx