version: '2.0'

services: 
  rest-api:
    build: .
    command: node src/server.js
    image: instant-mobile-receiver-api
    ports:
      - "8008:8008"
      - "8080:8080"
      - "5858:5858"
      - "443:443"
    volumes:
     - .:/usr/src/app  
    env_file: .env 
    links:
     - local-db

  rest-api-debug:
    build: .
    command: node-debug --web-host 0.0.0.0 src/server.js
    image: instant-mobile-receiver-api
    ports:
      - "8008:8008"
      - "8080:8080"
      - "5858:5858"
      - "443:443"
    volumes:
     - .:/usr/src/app      
    env_file: .env 
    
  local-db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
     - "8000:8000"

