version: '2.0'

services: 
  rest-api:
    build: .
    command: node-debug --web-host 0.0.0.0 app.js
    image: instant-mobile-receiver-api
    ports:
      - "8000:8000"
      - "8080:8080"
      - "5858:5858"
    volumes:
     - .:/usr/src/app      

